#Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
   - 3.4

before_install:
   - pip install pytest-cov
   - pip install coveralls

script:
   - py.test
   - coverage run py.test

after_success:
   - coveralls
