#Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
   - 3.3
   - 3.4
   - 3.5
   - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
   - pip install pytest-cov
   - pip install coveralls

script:
   - py.test
   - py.test --cov mmap_backed_array

after_success:
   - coveralls
